language: node_js
node_js:
- "4.1"
script:
- ./node_modules/.bin/docpress build
after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then ./node_modules/.bin/git-update-ghpages -e; fi
cache:
  directories:
  - node_modules
env:
  global:
  - GIT_NAME: Travis CI
  - GIT_EMAIL: nobody@nobody.org
  - GITHUB_REPO: rstacruz/backbone-patterns
  - GIT_SOURCE: _docpress
